[git]
origin = '...'
author = { name = 'Mojang', email = '...' }
committer = { name = 'Mojang', email = '...' }

[sources.'mojang/cfr']
mappings = 'mojang'
decompiler = 'cfr'

[branches.master]
source = 'mojang/cfr'
filter.exclude = ['20w14infinite']

[branches.20w14infinite]
source = 'mojang/cfr'
head = '20w14infinite'

[branches.test]
source = 'mojang/cfr'
base = '20w15a'
head = '20w16a'
