[git]
origin = '...' # The url of the origin remote saved in the local git repo
author = { name = 'Mojang', email = '...' }
committer = { name = 'Mojang', email = '...' }

# Specify custom versions of decompilers
[decompilers]
cfr = 'org.benf:cfr:0.151'
quiltflower = { url = "https://jitpack.io/", artifact = "com.github.QuiltMC:quiltflower:develop~1.6.0-SNAPSHOT"}

# Define a source set
[sources.'mojang/quiltflower']
mappings = 'mojang'
decompiler = 'quiltflower'

# Define a branch based on the mojang/quiltflower
[branches.main]
source = 'mojang/quiltflower'
